In [1]:
import numpy as np

a = np.zeros((5, 5), dtype = int)
a[0][0] = 1
a[4][4] = 7
a[0][4] = 2
a[2][0] = 3
a[2][2] = 4
a[2][4] = 5
a[4][0] = 6
print(a)

sub_matrix = np.zeros((3, 3), dtype = int)
#0->2
count = 0
n = a.shape[1] -  2
for k in range(n):
    for i in range(n):
        for j in range(n):
            sub_matrix[j] = a[j+k, i:i+3]
        print(sub_matrix)
        count += 1

print(count)

[[1 0 0 0 2]
 [0 0 0 0 0]
 [3 0 4 0 5]
 [0 0 0 0 0]
 [6 0 0 0 7]]
[[1 0 0]
 [0 0 0]
 [3 0 4]]
[[0 0 0]
 [0 0 0]
 [0 4 0]]
[[0 0 2]
 [0 0 0]
 [4 0 5]]
[[0 0 0]
 [3 0 4]
 [0 0 0]]
[[0 0 0]
 [0 4 0]
 [0 0 0]]
[[0 0 0]
 [4 0 5]
 [0 0 0]]
[[3 0 4]
 [0 0 0]
 [6 0 0]]
[[0 4 0]
 [0 0 0]
 [0 0 0]]
[[4 0 5]
 [0 0 0]
 [0 0 7]]
9


In [31]:
import abC as ab
import numpy as np
import datetime as dt

LIMIT_TIME = 5

a = ab.TicTacToe(3)
a.set(2, 1, "X")
a.draw_board()
b = ab.AlphaBeta(a)

def limitAlphaBeta(a, b):
    start_time = dt.datetime.now()
    end_time = start_time + dt.timedelta(0, LIMIT_TIME)
    depth = 1
    best = None
    while True:
        current_time = dt.datetime.now()
        if current_time > end_time:
            break;
        best = b.alpha_beta_search(a, "O", current_time, end_time - current_time)
        
        depth += 1
    return best

r = limitAlphaBeta(a, b)
r.draw_board()
#x = b.alpha_beta_search(a, "O")
#x.draw_board()





-| -| -| 
-| -| -| 
-| X| -| 

O| -| -| 
-| -| -| 
-| X| -| 



In [20]:
a = TicTacToe(5)
a.set(1, 2, "X")
a.set(2, 3, "X")
a.set(3, 4, "X")
a.draw_board()
print(a.get_last_move())


-| -| -| -| -| 
-| -| X| -| -| 
-| -| -| X| -| 
-| -| -| -| X| 
-| -| -| -| -| 



AttributeError: 'TicTacToe' object has no attribute 'get_last_move'

In [33]:
import random as rd

for i in range(30):
    print(rd.randint(0, 9))

4
7
2
0
9
2
3
6
1
7
1
0
4
4
8
7
8
3
8
6
8
1
7
6
4
7
2
8
2
3


kar ngy trang tiusn dungj lowns nhất thế giới là ả ma toi ngu ngu ngu hahahahha
**Ả tong teo**
# hibara
$a^2 + b + c $